trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Dev

stages:

- template: pipelines/verify.yml

- template: pipelines/security.yml

- template: pipelines/validation.yml

- template: pipelines/plan.yml

# - template: pipelines/approval.yml

# - template: pipelines/apply.yml
