trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Dev

stages:

# =====================================================
# Stage 0 - Verify Build Agent
# =====================================================

- stage: Verify
  displayName: "Verify Build Agent"

  jobs:
    - job: VerifyAgent
      displayName: "Agent Information"

      steps:
        - checkout: self

        - script: |
            echo "========== Agent Information =========="
            echo "Agent Name: $(Agent.Name)"
            echo "Agent OS: $(Agent.OS)"
            echo "Agent Machine Name: $(Agent.MachineName)"
            echo "Working Directory:"
            pwd

            echo ""
            echo "========== Repository =========="
            ls -la

            echo ""
            echo "========== Repository Structure =========="
            find . -maxdepth 3
          displayName: "Display Agent & Repository Details"

# =====================================================
# Stage 1 - Security Setup
# =====================================================

- stage: SecurityScan
  displayName: "DevSecOps Security Gate"
  dependsOn: Verify

  jobs:
    - job: SecurityCheck
      displayName: "Install Security Tools"

      steps:
        - checkout: self
          fetchDepth: 0

        # Verify Variable Group

        - script: |
            echo "Terraform Version : $(TF_VERSION)"
            echo "Environment       : $(ENVIRONMENT)"
            echo "Location          : $(LOCATION)"
          displayName: "Verify Variable Group"

        # Install Terraform (Manual Installation)

        - script: |
            sudo apt-get update
            sudo apt-get install -y unzip wget
            wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
            unzip terraform_$(TF_VERSION)_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform version
          displayName: "Install Terraform"


        # Install & Run GitLeaks

        - script: |
           GITLEAKS_VERSION=8.30.1
           mkdir /tmp/gitleaks
           cd /tmp/gitleaks
           wget https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
           tar -xzf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
           sudo mv gitleaks /usr/local/bin/
           chmod +x /usr/local/bin/gitleaks
           cd $(Build.SourcesDirectory)
           gitleaks version
           gitleaks dir . --verbose
          displayName: "Run GitLeaks Scan"

        # Install & Run TFLint

        - script: |
           TFLINT_VERSION=0.59.1
           mkdir /tmp/tflint
           cd /tmp/tflint
           wget https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip
           unzip tflint_linux_amd64.zip
           sudo mv tflint /usr/local/bin/
           chmod +x /usr/local/bin/tflint
           echo "==============================="
           echo "TFLint Version"
           echo "==============================="
           tflint --version
           echo ""
           echo "==============================="
           echo "Initializing and Running TFLint"
           echo "==============================="
           cd $(Build.SourcesDirectory)/Environment/Dev
           terraform init -backend=false
           tflint --init
           tflint --format compact || true
          displayName: "Run TFLint"
          continueOnError: true
          
        - script: |

           python3 -m pip install --upgrade pip

           pip3 install checkov==3.2.461

           checkov --version

           cd $(Build.SourcesDirectory)

           checkov \
              -d . \
              - framework terraform \
              --compact \
              --quit || true
          displayName: "RunCheckov"      
          continueOnError: true