trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Terraform-Dev

stages:
  - stage: Verify
    displayName: "Verify Build Agent"

    jobs:
      - job: VerifyAgent
        displayName: "Agent Information"

        steps:
          - checkout: self

          - script: |
              echo "========== Agent Information =========="
              echo "Agent Name: $(Agent.Name)"
              echo "Agent OS: $(Agent.OS)"
              echo "Agent Machine Name: $(Agent.MachineName)"
              echo "Working Directory:"
              pwd

              echo ""
              echo "========== Repository =========="
              ls -la

              echo ""
              echo "========== Repository Structure =========="
              find . -maxdepth 3
            displayName: "Display Agent & Repository Details"


  - stage: SecurityScan
    displayName: "Security Scan"
    dependsOn: Verify

    jobs:
     - job: SecurityCheck
       displayName: "Run Security Tools"

       steps:
        
        - checkout: self
          fetchDepth: 0

        #Install Terraform

        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: $(TF_VERSION)

        #Install GitLeaks
        - script: |
            curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | sh -s -- -b /usr/local/bin
            gitleaks version
          displayName: Install GitLeaks      
                    
        # Install TFLint
        - script: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            tflint --version
          displayName: Install TFLint

        # Install Checkov
        - script: |
            python3 -m pip install --upgrade pip
            pip3 install checkov
            checkov --version
          displayName: Install Checkov 