stages:
- stage: TerraformPlan
  displayName: "Terraform Plan"

  dependsOn: TerraformValidation
  condition: succeeded()

  jobs:
  - job: TerraformPlan
    displayName: "Terraform Plan"

    pool:
      vmImage: ubuntu-latest

    variables:
    - group: Terraform-Dev

    steps:

    # ============================================
    # Checkout Repository
    # ============================================

    - checkout: self

    # ============================================
    # Download Secure terraform.auto.tfvars
    # ============================================

    - task: DownloadSecureFile@1
      name: tfvars
      displayName: "Download terraform.auto.tfvars"

      inputs:
        secureFile: "terraform.auto.tfvars"

    # ============================================
    # Copy Secure File
    # ============================================

    - script: |
        cp $(tfvars.secureFilePath) $(Build.SourcesDirectory)/Environment/Dev/terraform.auto.tfvars

        echo "==============================="
        echo "Terraform Files"
        echo "==============================="

        ls -la $(Build.SourcesDirectory)/Environment/Dev

      displayName: "Copy terraform.auto.tfvars"

    # ============================================
    # Install Terraform
    # ============================================

    - script: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

        wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip

        unzip -o terraform_$(TF_VERSION)_linux_amd64.zip

        sudo mv terraform /usr/local/bin/

        terraform version

      displayName: "Install Terraform"

        # ============================================
    # Install Infracost
    # ============================================

    - script: |
        INFRACOST_VERSION=2.12.2

        wget https://github.com/infracost/infracost/releases/download/v${INFRACOST_VERSION}/infracost-linux-amd64.tar.gz

        tar -xzf infracost-linux-amd64.tar.gz

        sudo mv infracost-linux-amd64 /usr/local/bin/infracost

        chmod +x /usr/local/bin/infracost

        echo "==============================="
        echo "Infracost Version"
        echo "==============================="

        infracost --version

      displayName: "Install Infracost"  

    # ============================================
    # Terraform Init & Plan
    # ============================================

    - task: AzureCLI@2
      displayName: "Terraform Init & Plan"

      inputs:
        azureSubscription: "OTTApp-Azure-SC"
        scriptType: bash
        scriptLocation: inlineScript

        inlineScript: |

          echo "==============================="
          echo "Terraform Init"
          echo "==============================="

          cd $(Build.SourcesDirectory)/Environment/Dev

          terraform init

          echo ""

          echo "==============================="
          echo "Current Directory"
          echo "==============================="

          pwd

          echo ""

          echo "==============================="
          echo "Files"
          echo "==============================="

          ls -la

          echo ""

          echo "==============================="
          echo "Terraform Plan"
          echo "==============================="

          terraform plan -input=false -out=tfplan

    
    # ============================================
    # Run Infracost
    # ============================================

    - script: |

        echo "==============================="
        echo "Running Infracost"
        echo "==============================="

        export INFRACOST_API_KEY=$(INFRACOST_API_KEY)

        cd $(Build.SourcesDirectory)/Environment/Dev

        infracost breakdown \
          --path=tfplan \
          --format=table

      displayName: "Run Infracost"


    # ============================================
    # Publish Terraform Plan
    # ============================================

    - task: PublishPipelineArtifact@1
      displayName: "Publish Terraform Plan"

      inputs:
        targetPath: "$(Build.SourcesDirectory)/Environment/Dev/tfplan"
        artifact: "tfplan"