stages:
- stage: TerraformPlan
  displayName: "Terraform Plan"

  dependsOn: TerraformValidation
  condition: succeeded()

  jobs:
  - job: TerraformPlan
    displayName: "Terraform Plan"

    pool:
      vmImage: ubuntu-latest

    variables:
    - group: Terraform-Dev

    steps:

    - checkout: self

    # Install Terraform
    - script: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

        wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip

        unzip terraform_$(TF_VERSION)_linux_amd64.zip

        sudo mv terraform /usr/local/bin/

        terraform version
      displayName: "Install Terraform"

    # Terraform Init & Plan
    - task: AzureCLI@2
      displayName: "Terraform Init & Plan"

      inputs:
        azureSubscription: "OTTApp-Azure-SC"
        scriptType: bash
        scriptLocation: inlineScript

        inlineScript: |

          echo "==============================="
          echo "Terraform Init"
          echo "==============================="

          cd $(Build.SourcesDirectory)/Environment/Dev

          terraform init

          echo ""


          pwd

          ls -la
          echo "==============================="
          echo "Terraform Variables File"
          echo "==============================="
          ls -l terraform.tfvars

          echo "==============================="
          echo "Terraform Variables"
          echo "==============================="

          grep "^APGWs" terraform.tfvars || true

          echo ""

          terraform validate


          echo "==============================="
          echo "Terraform Plan"
          echo "==============================="

          terraform plan \
          -input=false \
          -var-file="terraform.tfvars" \
          -out=tfplan

    # Publish Plan Artifact
    - task: PublishPipelineArtifact@1
      displayName: "Publish Terraform Plan"

      inputs:
        targetPath: "$(Build.SourcesDirectory)/Environment/Dev/tfplan"
        artifact: "tfplan"